### ISSUE TITLE
add bower file

### ISSUE THREAD

**Issue by gbelmm** [joaquinnunez/jQuery-Rut-Plugin#1]
registrar en bower porfavor

http://bower.io/docs/creating-packages/

**Comment by pabloselin** [comment]
también agradecería que funcionara con bower. Es un buen módulo y muy útil su integración con jquery.validate. Gracias!

**Comment by joaquinnunez** [comment]
Hola, si lo pueden forkear hacer el cambio, feliz lo hago.

**Comment by gbelmm** [comment]
@joaquinnunez por favor

**Comment by joaquinnunez** [comment]
hola, ahora deberían poder hacer `bower install jquery-rut-plugin`

saludos.
